function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(CUDArt.CUDArt_gen.checkerror, (UInt32,))
    precompile(CUDArt.init, (Int64,))
    precompile(CUDArt.init, (Array{Int64, 1},))
    precompile(CUDArt.devices, (Array{Any, 1}, Function, Function,))
    precompile(CUDArt.device_reset, (Int64,))
    precompile(CUDArt.devices, (Array{Any, 1}, Function,))
    precompile(CUDArt.launch, (Array{Any, 1}, CUDArt.CuFunction, Int64, Tuple{Int64, Int64}, Tuple{CUDArt.CudaPitchedArray{Float64, 2}, Int64, Int64, Int64, UInt64, Float64},))
    precompile(CUDArt.launch, (Array{Any, 1}, CUDArt.CuFunction, Int64, Int64, Tuple{CUDArt.CudaArray{Float64, 2}, Int64, Float64},))
    precompile(CUDArt.launch, (Array{Any, 1}, CUDArt.CuFunction, Int64, Int64, Tuple{CUDArt.CudaPitchedArray{Int64, 1}, Int64, Int64, Int64, UInt64, Int64},))
    precompile(CUDArt.launch, (Array{Any, 1}, CUDArt.CuFunction, Int64, Int64, Tuple{CUDArt.CudaArray{Int32, 2}, Int64, Int32},))
    precompile(CUDArt.launch, (Array{Any, 1}, CUDArt.CuFunction, Int64, Tuple{Int64, Int64}, Tuple{CUDArt.CudaPitchedArray{Int32, 2}, Int64, Int64, Int64, UInt64, Int32},))
    precompile(CUDArt.launch, (Array{Any, 1}, CUDArt.CuFunction, Int64, Int64, Tuple{CUDArt.CudaArray{Int64, 1}, Int64, Int64},))
    precompile(CUDArt.call, (Type{CUDArt.CudaPitchedArray}, Type{Float64}, Tuple{Int64, Int64},))
    precompile(CUDArt.call, (Type{CUDArt.CudaPitchedArray}, Type{Int64}, Tuple{Int64},))
    precompile(CUDArt.call, (Type{CUDArt.CudaPitchedArray}, Type{UInt16}, Tuple{Int64, Int64},))
    precompile(CUDArt.call, (Type{CUDArt.CudaPitchedArray}, Type{Int32}, Tuple{Int64, Int64},))
    precompile(CUDArt.copy!, (Array{Any, 1}, CUDArt.CudaArray{Int64, 1}, Array{Int64, 1},))
    precompile(CUDArt.cudacopy!, (Array{Any, 1}, CUDArt.CudaPitchedArray{UInt16, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Array{UInt16, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.cudacopy!, (Array{Any, 1}, CUDArt.CudaPitchedArray{Float64, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Array{Float64, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.call, (Type{CUDArt.CudaPitchedArray}, Type{Float32}, Tuple{Int64},))
    precompile(CUDArt.copy!, (Array{Any, 1}, CUDArt.CudaArray{Float64, 2}, Array{Float64, 2},))
    precompile(CUDArt.cudacopy!, (Array{Any, 1}, Array{Float64, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, CUDArt.CudaPitchedArray{Float64, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.cudacopy!, (Array{Any, 1}, CUDArt.CudaPitchedArray{Int32, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Array{Int32, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.cudacopy!, (Array{Any, 1}, CUDArt.CudaPitchedArray{Int64, 1}, Tuple{Base.UnitRange{Int64}}, Array{Int64, 1}, Tuple{Base.UnitRange{Int64}},))
    precompile(CUDArt.cudacopy!, (Array{Any, 1}, Array{UInt16, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, CUDArt.CudaPitchedArray{UInt16, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.cudacopy!, (Array{Any, 1}, Array{Int64, 1}, Tuple{Base.UnitRange{Int64}}, CUDArt.CudaPitchedArray{Int64, 1}, Tuple{Base.UnitRange{Int64}},))
    precompile(CUDArt.cudacopy!, (Array{Any, 1}, CUDArt.CudaArray{UInt16, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, CUDArt.CudaPitchedArray{UInt16, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.cudacopy!, (Array{Any, 1}, Array{Int32, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, CUDArt.CudaPitchedArray{Int32, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.cudacopy!, (Array{Any, 1}, CUDArt.CudaPitchedArray{UInt16, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, CUDArt.CudaArray{UInt16, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.cudacopy!, (Array{Any, 1}, CUDArt.CudaPitchedArray{Float64, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, CUDArt.CudaPitchedArray{Float64, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.copy!, (Array{Any, 1}, CUDArt.CudaArray{UInt16, 2}, Array{UInt16, 2},))
    precompile(CUDArt.copy!, (Array{Any, 1}, CUDArt.CudaArray{Int32, 2}, Array{Int32, 2},))
    precompile(CUDArt.copy!, (Array{Any, 1}, CUDArt.CudaArray{Int32, 2}, CUDArt.HostArray{Int32, 2},))
    precompile(CUDArt.checkdrv, (Int32, ASCIIString,))
    precompile(CUDArt.devices, (Function, Array{Int64, 1},))
    precompile(CUDArt.close, (Int64,))
    precompile(CUDArt.close, (Array{Int64, 1},))
    precompile(CUDArt.call, (Type{CUDArt.CudaArray}, Type{Int64}, Tuple{Int64},))
    precompile(CUDArt.call, (Type{CUDArt.CudaArray}, Type{UInt16}, Tuple{Int64, Int64},))
    precompile(CUDArt.call, (Type{CUDArt.CudaArray}, Type{Int32}, Tuple{Int64, Int64},))
    precompile(CUDArt.size, (CUDArt.CudaPitchedArray{Float64, 2}, Int64,))
    precompile(CUDArt.call, (Type{CUDArt.CudaArray}, Type{Float32}, Tuple{Int64},))
    precompile(CUDArt.call, (Type{CUDArt.CudaArray}, Type{Float64}, Tuple{Int64, Int64},))
    precompile(CUDArt.size, (CUDArt.CudaPitchedArray{Int32, 2}, Int64,))
    precompile(CUDArt.capability, (Int64,))
    precompile(CUDArt.checkstrides_pitched, (CUDArt.CudaArray{UInt16, 2},))
    precompile(CUDArt.checkdrv, (Int32, UTF8String,))
    precompile(CUDArt.call, (Type{CUDArt.CudaArray}, Array{Float64, 2},))
    precompile(CUDArt.checkdrv, (Int32,))
    precompile(CUDArt.size, (CUDArt.CudaPitchedArray{UInt16, 2}, Int64,))
    precompile(CUDArt.size, (CUDArt.CudaPitchedArray{Int64, 1}, Int64,))
    precompile(CUDArt.stride, (CUDArt.CudaPitchedArray{Float64, 2}, Int64,))
    precompile(CUDArt.get_dim_x, (Tuple{Int64, Int64},))
    precompile(CUDArt.checkstrides_pitched, (CUDArt.CudaPitchedArray{Int32, 2},))
    precompile(CUDArt.checkstrides_pitched, (CUDArt.CudaPitchedArray{Float64, 2},))
    precompile(CUDArt.stride, (CUDArt.CudaPitchedArray{Int64, 1}, Int64,))
    precompile(CUDArt.checkstrides_pitched, (CUDArt.CudaPitchedArray{Int64, 1},))
    precompile(CUDArt.checkstrides_pitched, (CUDArt.CudaPitchedArray{UInt16, 2},))
    precompile(CUDArt.checkstrides_pitched, (Array{Float64, 2},))
    precompile(CUDArt.stride, (CUDArt.CudaPitchedArray{UInt16, 2}, Int64,))
    precompile(CUDArt.stride, (CUDArt.CudaPitchedArray{Int32, 2}, Int64,))
    precompile(CUDArt.pitchedptr, (CUDArt.CudaArray{UInt16, 2},))
    precompile(CUDArt.size, (CUDArt.CudaArray{UInt16, 2}, Int64,))
    precompile(CUDArt.checkstrides_pitched, (Array{Int32, 2},))
    precompile(CUDArt.checkstrides_pitched, (Array{UInt16, 2},))
    precompile(CUDArt.pitchedptr, (Array{Float64, 2},))
    precompile(CUDArt.pitchedptr, (Array{Int32, 2},))
    precompile(CUDArt.checkstrides_pitched, (Array{Int64, 1},))
    precompile(CUDArt.pitchedptr, (Array{UInt16, 2},))
    precompile(CUDArt.call, (Type{CUDArt.CuModule}, Function, ASCIIString,))
    precompile(CUDArt.pitchedptr, (Array{Int64, 1},))
    precompile(CUDArt.free, (CUDArt.CudaPitchedArray{Int64, 1},))
    precompile(CUDArt.get_dim_y, (Tuple{Int64, Int64},))
    precompile(CUDArt.copy!, (CUDArt.CudaPitchedArray{UInt16, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Array{UInt16, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.call, (Type{CUDArt.CuModule}, UTF8String, Bool,))
    precompile(CUDArt.call, (Type{CUDArt.CuModule}, ASCIIString, Bool,))
    precompile(CUDArt.call, (Type{CUDArt.CUDArt_gen.cudaPos}, Type{Int32}, Tuple{Int64, Int64},))
    precompile(CUDArt.copy!, (CUDArt.CudaPitchedArray{Float64, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Array{Float64, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.copy!, (Array{Int32, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, CUDArt.CudaPitchedArray{Int32, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.call, (Type{CUDArt.CUDArt_gen.cudaExtent}, Type{Int32}, Tuple{Int64, Int64},))
    precompile(CUDArt.copy!, (Array{Float64, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, CUDArt.CudaPitchedArray{Float64, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.call, (Type{CUDArt.CUDArt_gen.cudaPos}, Type{Float64}, Tuple{Int64, Int64},))
    precompile(CUDArt.copy!, (CUDArt.CudaPitchedArray{Int32, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, Array{Int32, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.similar, (CUDArt.CudaPitchedArray{Int64, 1}, Tuple{Int64},))
    precompile(CUDArt.CUDArt_gen.call, (Type{CUDArt.CUDArt_gen.cudaMemcpy3DParms}, Ptr{Void}, CUDArt.CUDArt_gen.cudaPos, CUDArt.CUDArt_gen.cudaPitchedPtr, Ptr{Void}, CUDArt.CUDArt_gen.cudaPos, CUDArt.CUDArt_gen.cudaPitchedPtr, CUDArt.CUDArt_gen.cudaExtent, UInt32,))
    precompile(CUDArt.similar, (CUDArt.CudaArray{Int64, 1}, Tuple{Int64},))
    precompile(CUDArt.copy!, (Array{Int64, 1}, Tuple{Base.UnitRange{Int64}}, CUDArt.CudaPitchedArray{Int64, 1}, Tuple{Base.UnitRange{Int64}},))
    precompile(CUDArt.copy!, (Array{UInt16, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, CUDArt.CudaPitchedArray{UInt16, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.copy!, (CUDArt.CudaPitchedArray{Int64, 1}, Tuple{Base.UnitRange{Int64}}, Array{Int64, 1}, Tuple{Base.UnitRange{Int64}},))
    precompile(CUDArt.call, (Type{CUDArt.CUDArt_gen.cudaExtent}, Type{UInt16}, Tuple{Int64, Int64},))
    precompile(CUDArt.call, (Type{CUDArt.CUDArt_gen.cudaPos}, Type{UInt16}, Tuple{Int64, Int64},))
    precompile(CUDArt.copy!, (CUDArt.CudaPitchedArray{Float64, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, CUDArt.CudaPitchedArray{Float64, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.call, (Type{CUDArt.CUDArt_gen.cudaExtent}, Type{Float64}, Tuple{Int64, Int64},))
    precompile(CUDArt.copy!, (CUDArt.CudaArray{UInt16, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, CUDArt.CudaPitchedArray{UInt16, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.copy!, (CUDArt.CudaPitchedArray{UInt16, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}}, CUDArt.CudaArray{UInt16, 2}, Tuple{Base.UnitRange{Int64}, Base.UnitRange{Int64}},))
    precompile(CUDArt.free, (CUDArt.CudaPitchedArray{Float32, 1},))
    precompile(CUDArt.call, (Type{CUDArt.CudaArray}, Base.UnitRange{Int64},))
    precompile(CUDArt.call, (Type{CUDArt.CuFunction}, CUDArt.CuModule, ASCIIString,))
    precompile(CUDArt.similar, (CUDArt.CudaPitchedArray{Int64, 1},))
    precompile(CUDArt.similar, (CUDArt.CudaArray{Int64, 1},))
    precompile(CUDArt.free, (CUDArt.CudaPitchedArray{Float64, 2},))
    precompile(CUDArt.call, (Type{CUDArt.CUDArt_gen.cudaExtent}, Type{Int64}, Tuple{Int64},))
    precompile(CUDArt.call, (Type{CUDArt.CUDArt_gen.cudaPos}, Type{Int64}, Tuple{Int64},))
    precompile(CUDArt.free, (CUDArt.CudaPtr{Float32},))
    precompile(CUDArt.getindex, (CUDArt.HostArray{Int32, 2}, Int64, Int64,))
    precompile(CUDArt.free, (CUDArt.CudaPtr{Int32},))
    precompile(CUDArt.free, (CUDArt.CudaPtr{Int64},))
    precompile(CUDArt.free, (CUDArt.CudaPtr{Float64},))
    precompile(CUDArt.to_host, (CUDArt.CudaArray{Float64, 2},))
    precompile(CUDArt.free, (CUDArt.CudaPtr{UInt16},))
    precompile(CUDArt.free, (CUDArt.CudaPtr{UInt8},))
    precompile(CUDArt.call, (Type{CUDArt.CudaPitchedArray}, Base.UnitRange{Int64},))
    precompile(CUDArt.cubox, (CUDArt.CudaPitchedArray{Float64, 2},))
    precompile(CUDArt.to_host, (CUDArt.CudaPitchedArray{Int32, 2},))
    precompile(CUDArt.call, (Type{CUDArt.CudaPtr}, Ptr{Int64},))
    precompile(CUDArt.to_host, (CUDArt.CudaPitchedArray{UInt16, 2},))
    precompile(CUDArt.pointer, (CUDArt.CudaPitchedArray{Int64, 1},))
    precompile(CUDArt.to_host, (CUDArt.CudaPitchedArray{Float64, 2},))
    precompile(CUDArt.to_host, (CUDArt.CudaPitchedArray{Int64, 1},))
    precompile(CUDArt.cubox, (CUDArt.CudaPitchedArray{Int32, 2},))
    precompile(CUDArt.call, (Type{CUDArt.CudaArray{Float32, 1}}, CUDArt.CudaPtr{Float32}, Tuple{Int64}, Int64,))
    precompile(CUDArt.cubox, (CUDArt.CudaPitchedArray{Int64, 1},))
    precompile(CUDArt.copy, (CUDArt.CudaPtr{Float64},))
    precompile(CUDArt.to_host, (CUDArt.CudaArray{Int32, 2},))
    precompile(CUDArt.to_host, (CUDArt.CudaArray{UInt16, 2},))
    precompile(CUDArt.to_host, (CUDArt.CudaArray{Int64, 1},))
    precompile(CUDArt.call, (Type{CUDArt.CudaPtr}, Ptr{UInt8},))
    precompile(CUDArt.device, (Int64,))
    precompile(CUDArt.call, (Type{CUDArt.CudaArray{UInt16, 2}}, CUDArt.CudaPtr{UInt16}, Tuple{Int64, Int64}, Int64,))
    precompile(CUDArt.copy!, (CUDArt.CudaPitchedArray{Float64, 2}, Array{Float64, 2},))
    precompile(CUDArt.call, (Type{CUDArt.CudaPtr}, Ptr{Int32},))
    precompile(CUDArt.call, (Type{CUDArt.CudaPtr}, Ptr{UInt16},))
    precompile(CUDArt.free, (CUDArt.CudaArray{Float64, 2},))
    precompile(CUDArt.call, (Type{CUDArt.CudaArray{Int32, 2}}, CUDArt.CudaPtr{Int32}, Tuple{Int64, Int64}, Int64,))
    precompile(CUDArt.call, (Type{CUDArt.CudaPtr}, Ptr{Float32},))
    precompile(CUDArt.call, (Type{CUDArt.CudaPtr}, Ptr{Float64},))
    precompile(CUDArt.call, (Type{CUDArt.CudaPitchedArray{Int64, 1}}, CUDArt.CUDArt_gen.cudaPitchedPtr, Tuple{Int64}, Int64,))
    precompile(CUDArt.call, (Type{CUDArt.CudaPitchedArray{Float64, 2}}, CUDArt.CUDArt_gen.cudaPitchedPtr, Tuple{Int64, Int64}, Int64,))
    precompile(CUDArt.call, (Type{CUDArt.CudaPitchedArray{Float32, 1}}, CUDArt.CUDArt_gen.cudaPitchedPtr, Tuple{Int64}, Int64,))
    precompile(CUDArt.call, (Type{CUDArt.CudaPitchedArray{UInt16, 2}}, CUDArt.CUDArt_gen.cudaPitchedPtr, Tuple{Int64, Int64}, Int64,))
    precompile(CUDArt.call, (Type{CUDArt.CudaArray{Float64, 2}}, CUDArt.CudaPtr{Float64}, Tuple{Int64, Int64}, Int64,))
    precompile(CUDArt.call, (Type{CUDArt.CudaPitchedArray{Int32, 2}}, CUDArt.CUDArt_gen.cudaPitchedPtr, Tuple{Int64, Int64}, Int64,))
    precompile(CUDArt.call, (Type{CUDArt.CudaArray{Int64, 1}}, CUDArt.CudaPtr{Int64}, Tuple{Int64}, Int64,))
    precompile(CUDArt.copy!, (CUDArt.CudaPitchedArray{Int32, 2}, Array{Int32, 2},))
    precompile(CUDArt.cubox, (CUDArt.CudaArray{Float64, 2},))
    precompile(CUDArt.copy!, (Array{Int32, 2}, CUDArt.CudaArray{Int32, 2},))
    precompile(CUDArt.cubox, (CUDArt.CudaArray{Int64, 1},))
    precompile(CUDArt.cubox, (CUDArt.CudaArray{Int32, 2},))
    precompile(CUDArt.copy!, (CUDArt.CudaPitchedArray{UInt16, 2}, Array{UInt16, 2},))
    precompile(CUDArt.cubox, (Float64,))
    precompile(CUDArt.copy!, (CUDArt.CudaArray{UInt16, 2}, CUDArt.CudaPitchedArray{UInt16, 2},))
    precompile(CUDArt.copy!, (CUDArt.CudaPitchedArray{UInt16, 2}, CUDArt.CudaArray{UInt16, 2},))
    precompile(CUDArt.copy!, (CUDArt.CudaPitchedArray{Int64, 1}, Array{Int64, 1},))
    precompile(CUDArt.size, (CUDArt.CudaArray{Int64, 1},))
    precompile(CUDArt.size, (CUDArt.CudaArray{Float64, 2},))
    precompile(CUDArt.cubox, (UInt64,))
    precompile(CUDArt.size, (CUDArt.CudaPitchedArray{Float64, 2},))
    precompile(CUDArt.copy!, (CUDArt.HostArray{Int32, 2}, CUDArt.CudaArray{Int32, 2},))
    precompile(CUDArt.pointer, (CUDArt.CudaPitchedArray{Float64, 2},))
    precompile(CUDArt.cubox, (Int64,))
    precompile(CUDArt.get!, (CUDArt.CudaPitchedArray{Float64, 2}, CUDArt.CudaPitchedArray{Float64, 2}, Tuple{Int64, Base.UnitRange{Int64}}, Float64,))
    precompile(CUDArt.size, (CUDArt.CudaPitchedArray{Int64, 1},))
    precompile(CUDArt.cubox, (Int32,))
    precompile(CUDArt.pointer, (CUDArt.CudaArray{Float64, 2},))
    precompile(CUDArt.similar, (CUDArt.CudaPitchedArray{Int64, 1}, Type{Float32},))
    precompile(CUDArt.similar, (CUDArt.CudaArray{Int64, 1}, Type{Float32},))
    precompile(CUDArt.fill!, (CUDArt.CudaArray{Int64, 1}, Int64,))
    precompile(CUDArt.fill!, (CUDArt.CudaArray{Float64, 2}, Int64,))
    precompile(CUDArt.fill!, (CUDArt.CudaPitchedArray{Float64, 2}, Float64,))
    precompile(CUDArt.fill!, (CUDArt.CudaPitchedArray{Int64, 1}, UInt8,))
    precompile(CUDArt.fill!, (CUDArt.CudaArray{Int64, 1}, UInt8,))
    precompile(CUDArt.fill!, (CUDArt.CudaArray{Float64, 2}, Float64,))
    precompile(CUDArt.fill!, (CUDArt.CudaArray{Int32, 2}, Int64,))
    precompile(CUDArt.fill!, (CUDArt.CudaPitchedArray{Int32, 2}, Int64,))
    precompile(CUDArt.eltype, (CUDArt.CudaArray{Int64, 1},))
    precompile(CUDArt.fill!, (CUDArt.CudaPitchedArray{Float64, 2}, Int64,))
    precompile(CUDArt.fill!, (CUDArt.CudaPitchedArray{Int64, 1}, Int64,))
    precompile(CUDArt.eltype, (CUDArt.CudaArray{Float32, 1},))
    precompile(CUDArt.eltype, (CUDArt.CudaPitchedArray{Float32, 1},))
    precompile(CUDArt.eltype, (CUDArt.CudaPitchedArray{Int64, 1},))
    precompile(CUDArt.devices, (Function,))
end
